name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [
          11, # Minimum
          16  # Current
        ],
        loom: [
          # Upstream
          fabric0_8, # Minimum
          fabric0_9, # Experimental

          # Arch
          arch0_7_2, # Minimum
          arch0_8_0, # Supported
          arch0_7_3, # Experimental
          arch0_9_0  # Experimental
        ],
        exclude:
          - java: 11
            loom: fabric0_8
          - java: 11
            loom: fabric0_9
          - java: 11
            loom: arch0_8_0
          - java: 11
            loom: arch0_9_0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        env:
          TEST_LOOM_VARIANT: ${{ matrix.loom }}
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
