name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [
          17 # Minimum (0.11+)
        ]
        loom: [
          # Upstream
          "fabric-loom:0.8-SNAPSHOT",  # Barely alive
          "fabric-loom:0.9-SNAPSHOT",  # Stable
          "fabric-loom:0.11-SNAPSHOT", # Stable
          "fabric-loom:0.12-SNAPSHOT", # Future version

          # Arch
          "dev.architectury.loom:0.7.2-SNAPSHOT",  # Barely alive
          "dev.architectury.loom:0.7.4-SNAPSHOT",  # Barely alive
          "dev.architectury.loom:0.10.0-SNAPSHOT", # Stable
          "dev.architectury.loom:0.11.0-SNAPSHOT", # Stable

          # Quilt (I'd imagine this is temporary since it's their decompiler)
          "org.quiltmc.loom:0.12.+", # Experimental
        ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        env:
          TEST_LOOM_VARIANT: ${{ matrix.loom }}
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
