name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [
          11, # Minimum
          16  # Current
        ]
        loom: [
          # Upstream
          "fabric-loom:0.8-SNAPSHOT", # Minimum
          "fabric-loom:0.9-SNAPSHOT", # Experimental

          # Arch
          "dev.architectury.loom:0.7.2-SNAPSHOT", # Minimum
          "dev.architectury.loom:0.8.0-SNAPSHOT", # Supported
          "dev.architectury.loom:0.7.3-SNAPSHOT", # Experimental
          "dev.architectury.loom:0.9.0-SNAPSHOT"  # Experimental
        ]
        exclude:
          - java: 11
            loom: fabric0_8
          - java: 11
            loom: fabric0_9
          - java: 11
            loom: arch0_8_0
          - java: 11
            loom: arch0_9_0
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        env:
          TEST_LOOM_VARIANT: ${{ matrix.loom }}
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
